name: Building

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build

      - name: Discord Notification
        uses: appleboy/discord-action@master
        if: always() # Ensures this runs even if previous steps fail
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **Workflow:** ${{ github.workflow }}
            **Status:** ${{ job.status }}
            **Commit:** ${{ github.event.head_commit.message }}
            **Link:** https://github.com{{ github.repository }}/actions/runs/${{ github.run_id }}
